name: Financial Data Pipeline

on:
  schedule:
    # Se ejecuta todos los días a las 9 AM
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests psycopg2-binary python-dotenv

      - name: Run Python script
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: python get_data.py
